#!/usr/bin/env node 
 
//author  : Umar aka jukoo  j_umar@outlook.com   <github.com/jukoo> 

__KERNEL__v1 :   
module 
["exports"] =  {
    
    ["@libs"]  :  { 
         menu  : require("./menu") , 
         utils : require("./utils") 
    } ,
    ["@node_module"] : { 
        _ejs_  : require("electron"),
        url    : require("url"), 
        path   : require("path"), 
        fs     : require("fs"),
        os     : require("os") 
    },
    ["@config"]: {
        defconf : require("./config") 
    } , 
   ["@extra"]  :  {  
       xpress  : require("express"), 
       io_socket:  require("socket.io")
   }
}
